# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cebe83147f8d6364dbc28bd28caf221a23fc53e8465895b41f3c64897e060e1597365885e673596c151ec20f648d801a823a2e94cfac44a621ce2278c990db24

test:
  secret_key_base: 3e7f16f3be2bc95cd86e8ffd8b7a1ff880e68dbc4a4fa236b40f0cf18faa7707f5546d890042946bfb053904021785ac57e3d73c6752756c39f7ceae2921f5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
